user_login_alarm/input.tf, user_login_alarm/main.tf
This is mainly used to notify us when a break-glass account logs into an
AWS account but can be used to track any accounts we want to.
This is related to https://github.com/cds-snc/site-reliability-engineering/issues/203
=> feat: alarm for when user logins using console

user_login_alarm/README.md, user_login_alarm/input.tf, user_login_alarm/main.tf
- Fix the alarm so it uses the metric name not the alarm name
- Split up the alarm so we have one for success and one for failures
- Allow the user to set the number of failed attempts before an alarm
goes off
- Change the unit to a Count (not sure we actually need to do this)
=> fix: handle success/failures and use proper metric

README.md, bin/generate-docs.sh, pub_priv_vpc/README.md, pub_priv_vpc/defaults.tf, pub_priv_vpc/flowlogs.tf, pub_priv_vpc/inputs.tf, pub_priv_vpc/locals.tf, pub_priv_vpc/main.tf, pub_priv_vpc/outputs.tf, pub_priv_vpc/routetable.tf
- Creates a VPC that has two subnets 1 public and 1 private.
- Adds an Inet gateway to the public subnet, adds a nat gateway to the
private subnet.
- Attaches an elastic IP to the VPC.
- Cleasr out default sg, route table, and nacl
- Add flowlogs
=> feat: add a module that creates a pub/priv vpc

rds/outputs.tf, rds/secret.tf
Exposes the proxy endpoint and the connection string as outputs. 
Adds the proxy connection string as a secret
=> feat: store the proxy connection string and expose it

vpc/README.md, vpc/inputs.tf, vpc/nacl.tf, vpc/outputs.tf
Adds a NACL that is connected to all subnets. 
Allows the user to unblock ssh and rdp ports
Exports the nacl id so we can attach more rules
=> feat: add a nacl to the vpc

rds/secret.tf
We were using the wrong connection string type and this fixes that. 
Closes #30
=> fix: use postgresql instead of postgres

.github/workflows/terratest.yml, user_login_alarm/.checkov.yml, user_login_alarm/examples/alarm_actions/main.tf, user_login_alarm/examples/alarm_actions/outputs.tf, user_login_alarm/examples/alarm_actions/provider.tf, user_login_alarm/test/alarm_actions_test.go, user_login_alarm/test/cloudwatch_test.go, user_login_alarm/test/no_actions_test.go
* Adds a workflow that runs the modules that have Terratests against the `TerraformModules-Test` AWS account.
* Also includes a `user_alarm_action` example with SNS topics and the associated tests.
Closes #12
=> feat: CI workflow to run Terratests

.devcontainer/devcontainer.json
This makes sure `gopls` is installed as part of the devcontainer build.
=> fix: install Go language server automatically in devcontainer

vpc/README.md, vpc/examples/high_availability/main.tf, vpc/examples/single_zone/main.tf, vpc/flowlogs.tf, vpc/inputs.tf, vpc/nacl.tf, vpc/test/high_availability_test.go, vpc/test/single_zone_test.go, vpc/test/vpc_test.go
This adds four new variables that control Network ACL rules to allow requests into and out of the VPC:
* `allow_https_request_out`: allow resources to send 443 requests out to the internet. 
* `allow_https_request_out_response`: allow resources to receive a response to their request out.
* `allow_https_request_in`: allow users to send 443 requests into the VPC from the internet.
* `allow_https_request_in_response`: allow a response to be sent back to the user from the VPC.
The allow for ephemeral ports is because NAT Gateways use them to track the network address translation.
It also includes a fix which prevents the flow log CloudWatch log group from being recreated after it has been deleted.
=> feat: allow HTTPS ingress or egress from the VPC

vpc/main.tf
These Public/Private tags can be used to filter subnets with the `data.aws_subnet` resource.
=> feat: add subnet tags to identify Public/Private

rds/examples/mysql_cluster/main.tf, rds/examples/postgresql_cluster/main.tf, rds/input.tf, rds/test/mysql_test.go, rds/test/postgresql_test.go
Allow hyphens and underscores in the RDS `database_name` input.
=> fix: RDS database_name input validation

lambda/permissions.tf
The current statement ID is not valid when using an arn so just replace
with the index of the arn in the list of topics to trigger
=> fix: remove arn from sns topic arn in stmt id

rds/README.md, rds/main.tf
Latest version of the RDS module errors with the below. I suspect this is because the service linked name doesn't exist.
Closes #87
=> feat: add rds service linked name

rds/README.md, rds/main.tf
Reverts cds-snc/terraform-modules#86
Service role was auto created by AWS. Looks like I ran into a race condition between proxy creation and the service role being available. Re-running the TF apply did the trick
=> Revert "feat: add rds service linked name"

.devcontainer/Dockerfile, vpc/README.md, vpc/main.tf
using default tags + modules makes the plan always show +tag. This will test merging the tags so that existing tags don't get flagged in the diff.
Also added python compile libraries since the devcontainer was failing to build since it couldn't compile some dependencies.
=> feat: merge default tags and fix devcontainer

lambda/README.md, lambda/output.tf, vpc/README.md, vpc/main.tf
- Need to output invoke_arn so the lambda can be integrated with a api gateway
- Revert default tag merging since there are alot of resources that dont support tags which will cause plans to contain too many unchanged items since the tags will flap
=> feat: output lambda invoke arn for api gateway integrations

rds/README.md, rds/examples/mysql_cluster/main.tf, rds/input.tf, rds/main.tf
By allowing control over the RDS cluster instance performance insights
configuration, people will be able to use smaller MySQL DB instances.
=> feat: RDS instance control performance insights

.github/workflows/conftest/test_plan.tf, .modules, gh_oicd_role/Makefile, gh_oicd_role/README.md, gh_oicd_role/input.tf, gh_oicd_role/locals.tf, gh_oicd_role/main.tf, gh_oicd_role/output.tf
Allows authentication in github workflows using Open ID Connect, this
allows us to authenticate with an AWS Account using Open ID Connect.
This allows for more secure authentication as keys are rotated every
time an authentication occurs.
I was able to authenticate using this module to my scratch account:
Closes https://github.com/cds-snc/site-reliability-engineering/issues/359
=> feat: Github Open ID Connect Role in AWS

S3/README.md, S3/examples/basic_bucket/main.tf, S3/examples/public_bucket/main.tf, S3/examples/replication_bucket/iam.tf, S3/examples/replication_bucket/main.tf, S3/examples/replication_bucket/provider.tf, S3/input.tf, S3/main.tf, S3/test/basic_bucket_test.go, S3/test/public_bucket_test.go, S3/test/replication_bucket_test.go
Add the ability to create s3 bucket replication rules.
Also removes the hardcoded bucket names from the s3 tests to prevent failures related to bucket names already being taken.
=> feat: s3 replication config

attach_tf_plan_policy/main.tf
Access to write to Dynamodb state table's was not working due to the missing wildcard for the table in the ARN
=> fix: dynamodb arn wildcard table name

attach_tf_plan_policy/README.md, attach_tf_plan_policy/main.tf
I had the readonly role attachement outside of the module, figured it
would be better to bring it in.
=> fix: add the readonly role into this module

S3/main.tf
Update to allow the S3 bucket's replication rule to specify if delete
markers are replicated to the destination bucket.
This is being done to support the Cloud Based Sensor so that
satellite buckets can have a shorter expiration time and save
storage costs.
=> feat: S3 delete marker replication status

sentinel_forwarder/input.tf
This bumps the layer for sentinel forwarder lambda to the latest version (https://github.com/cds-snc/aws-sentinel-connector-layer/pull/3)
=> feat: bumps the sentinel layer to version six

S3/versions.tf, S3_log_bucket/versions.tf
This module does not work with the new AWS v4 Provider, tests are
failing because it gets the latest verion of the provider.
=> feat: Pin s3 buckets to < 4

.modules, README.md, S3/README.md, S3/main.tf, S3_log_bucket/README.md, S3_log_bucket/main.tf, aws_goc_password_policy/Makefile, aws_goc_password_policy/README.md, aws_goc_password_policy/main.tf, gh_oidc_role/README.md, gh_oidc_role/main.tf, sentinel_forwarder/README.md
Adds a password policy that aligns with the published Guidance
from the Government of Canada
https://www.canada.ca/en/government/system/digital-government/online-security-privacy/password-guidance.html
Also fixes some issues with docs.
=> feat: add GOC Password Policy for AWS

.devcontainer/devcontainer.json, .modules, sns/Makefile, sns/README.md, sns/input.tf, sns/locals.tf, sns/main.tf, sns/output.tf
Closes #40. This PR adds a SNS module that enforces the use of a customer managed KMS key with the correct settings for service and IAM users.
Description: A wrapper on the SNS module that enfores a customer managed KMS key. You can either supply your own KMS ARN as `kms_master_key_id` or let the module create their own key. If you choose to let the module create a KMS key it will also include an IAM policy that allows access from the root user of the account. You can also supply service like `s3.amazonaws.com` or `sns.amazonaws.com` in the `kms_event_sources` list, as well as IAM roles in the `kms_iam_sources` list who will then have  `kms:Decrypt*` and `kms:GenerateDataKey*` permissions on the key.
=> feat: adds a SNS module that enforces the use of a CM KMS

gh_oidc_role/README.md, vpc/README.md, vpc/outputs.tf
Access to cidr blocks to be used in security groups that are behind a network load balancing. cidr blocks needed since network load balancers don't support security groups.
=> feat: output vpc subnet cidr blocks

vpc/README.md, vpc/examples/custom_cidr_and_subnets/main.tf, vpc/examples/custom_cidr_and_subnets/provider.tf, vpc/inputs.tf, vpc/main.tf, vpc/test/custom_cidr_and_subnets_test.go
Ability to provide specific CIDR and public/private subnets when creating a VPC. Feature required since VPC peering does not allow overlapping CIDR ranges between the two VPC's being peered.
=> feat: provide cidr and private/public subnets for vpc

notify_slack/notify_slack/notify_slack.py, notify_slack/notify_slack/notify_slack_test.py
Update the Slack request to send JSON data rather than
URL encoded form data, which is the default for
`urllib.request.Request`.
This is being done so the module works with both the
SRE bot's Slack webhooks as well as the default Slack
webhooks.
=> fix: lambda to send JSON request

.gitignore, .modules, gh_oidc_role/main.tf, guardduty/Makefile, guardduty/README.md, guardduty/input.tf, guardduty/locals.tf, guardduty/main.tf, guardduty/output.tf, guardduty/providers.tf, guardduty_member/Makefile, guardduty_member/README.md, guardduty_member/input.tf, guardduty_member/locals.tf, guardduty_member/main.tf, guardduty_member/providers.tf
Adds a module that enables guardduty in a region and setups a
delegated admin account with a detector in it.
Adds a module that adds a member account, this is only needed for
accounts created before the guardduty module was created.
Ignore the downloaded conftest policies
*****Please note this may not work so expect potential follow up PRs**
=> feat: add guardduty and guardduty member modules

.github/workflows/assets/aws-nuke-config.yml
This repos aws nuke config was missing all the modifications related to cloud based sensor and security automation from site-reliability-engineering
Unsure if adding the below will interfere with terratests:
- GuardDutyDetector-
- IAMOpenIDConnectProvider
- KMSKey
=> fix: exclude cbs and secops resources from aws nuke

.github/workflows/assets/aws-nuke-config.yml
Remove the Terraform modules AWS account from the `aws-nuke`
blocklist since this is preventing the workflow from running properly.
=> fix: remove TF modules AWS account from blocklist

.github/workflows/conftest/test_plan.tf, S3/versions.tf
Upgrading s3 aws provider as AFT Module requires > 4.9.0
BREAKING CHANGE: Upgrading major version of AWS Provider
=> feat!: Upgrade required AWS Version

S3_log_bucket/versions.tf
We missed upgrading the required providers for the s3 log bucket module.
This brings it in line with all the other modules in the repo.
=> fix: s3_log_bucket required providers

S3_scan_object/input.tf
Update docker image tag to include the fix for an SNS message
checksum with a value of `None`.
* cds-snc/scan-files#158
=> chore: bump S3 scan object docker image tag

S3_scan_object/input.tf
Update the S3 scan object docker image to include the fix that
prevents scans of S3 folder objects.
* cds-snc/scan-files#162
=> chore: S3 scan object bump docker image

S3_scan_object/lambda/main.py, S3_scan_object/lambda/main_test.py
Add a `RequestId` UUID to the event used to invoke the `s3-scan-object`
lambda.  This will be used to track requests as they flow through the
different components of the system.
=> feat: add `RequestId` to forwarded event payload

S3_scan_object/README.md, S3_scan_object/input.tf
Update the `S3 scan object` module to remove the unused
`scan_files_url` input.  This input is no longer needed after
the switch to a centralized scanning architecture.
* cds-snc/scan-files#182
=> fix: remove unused `scan_files_url` input

S3_scan_object/README.md, S3_scan_object/input.tf, S3_scan_object/main.tf
Update the S3 scan object transport lambda's reserved concurrency to
be configurable, with a default of `10`.  This is because an AWS account
cannot have a total `UnreservedConcurrentExecution` below 10 for all
functions.
* cds-snc/scan-files#182
=> fix: configure lambda reserved concurrency

S3_scan_object/.checkov.yml, S3_scan_object/README.md, S3_scan_object/alarms.tf, S3_scan_object/examples/simple/main.tf, S3_scan_object/input.tf
Update the `S3_scan_object` module to add an optional
metric filter and CloudWatch alarm to alert on failed
invocations of the transport lambda.
The metric filter and alarm will only be created if an
optional SNS topic ARN is provided.
* Closes #144
=> feat: add alarm for failed lambda invocations

S3_scan_object/README.md, S3_scan_object/alarms.tf, S3_scan_object/examples/simple/main.tf, S3_scan_object/input.tf
Update the S3 scan object module to allow users to specify
different SNS topics for Alarm and OK CloudWatch alarm actions.
* #144
=> feat: add SNS topic inputs for Alarm and OK actions

S3_scan_object/lambda/main.py, S3_scan_object/lambda/main_test.py
Update the transport lambda to use its `context.aws_request_id` as the
request ID that's passed into Scan Files to correlate log messages.
* Closes cds-snc/scan-files#199
=> feat: use `aws_request_id` as common UUID

rds/README.md, rds/input.tf, rds/main.tf
Update the cluster to provide an option that allows for immediate
DB engine upgrades, rather than during the maintenance
window.
=> feat: allow DB engine upgrades to apply immediately

athena_access_logs/main.tf
Update the Athena access log module to set `force_destroy` on
the database and workgroup.  This will make it easier for
projects using the module to remove these resources by 
allowing them to be deleted even if they contain data.
Force destroy is safe in this case because the database is
only a copy of the data which exists in the S3
access log bucket.
=> fix: force destroy Athena DB and workgroup

lambda/README.md, lambda/output.tf
This PR adds the `version` of a lambda function as an available output.
=> feat: add version output for lambda module

gh_oidc_role/main.tf
Switches internally from creating resources using count to for_each. 
This change will more than likely be breaking and will cause the apply to fail partway through, especially if you haven't migrated to the globally managed OIDC Roles here at CDS. 
Since at the time of me creating this PR there are only two accounts using those roles I'll assume this will break stuff for everyone so I will go up a major vversion when releasing this.
=> feat: use for_each instead of count

.devcontainer/Dockerfile
Update the devcontainer to pin the version of checkov installed as the latest version currently does not install because of a dependency conflict.
- bridgecrewio/checkov#3649
=> fix: pin checkov install in devcontainer

sentinel_forwarder/README.md, sentinel_forwarder/input.tf, sentinel_forwarder/main.tf, sentinel_forwarder/outputs.tf
This PR adds the ability for the sentinel forwarder lambda to be triggered from cloudwatch logs subscriptions. The pattern and the definition are outside of the scope of the module and therefore it only takes the arn of the cloudwatch log of the subscription.
For example, assume you have a cloudwatch log with arn `arn:aws:logs:ca-central-1:ACCOUNT:log-group:/aws/lambda/Foo`
Then you would configure the module the following way:
```
module "forwarder" {
source            = "github.com/cds-snc/terraform-modules?ref=0305826b0ed74cf01dcfce2065bdffa7280179ec//sentinel_forwarder"
function_name     = "sentinel-cloud-watch-forwarder"
billing_tag_value = "billing_tag_value"
customer_id = "customer_id"
shared_key  = "shared_key"
cloudwatch_log_arns = …
```
=> feat: Add Cloudwatch subscriptions as valid trigger

.github/workflows/terratest.yml
With Renovate updates triggering weekly, we're getting a lot of unneeded runs against all the TF modules.  Test workflows will now only trigger if the module code or test files change.
=> chore: remove Terratest trigger on workflow file

lambda/README.md, lambda/input.tf, lambda/main.tf
Update the lambda module to allow specifying ephemeral storage in the `/tmp` directory to a value above the default 512MB.
- cds-snc/scan-files#472
=> feat: lambda function ephemeral storage

S3/Makefile, S3_log_bucket/Makefile, S3_scan_object/Makefile, athena_access_logs/Makefile, attach_tf_plan_policy/Makefile, auto_revoke_sg_rules/Makefile, aws_goc_password_policy/Makefile, bin/scaffold.sh, exposed_iam_credentials_disabler/Makefile, gh_oidc_role/Makefile, guardduty/Makefile, guardduty_member/Makefile, lambda/Makefile, lambda_response/Makefile, notify_slack/Makefile, rds/Makefile, resolver_dns/Makefile, sentinel_alert_rule/Makefile, sentinel_forwarder/Makefile, sns/Makefile, user_login_alarm/Makefile, vpc/Makefile
- remove .terraform.lock.hcl and .terraform directory.
- add the rm command to scaffold.sh
- closes #212
=> Fix: doc check fails if .terraform or terraform.lock.hcl exists

vpc/nacl.tf
Changed cidr rules to any address (0.0.0.0/0) to block ports 22 and 3389. This was needed in order to meet ATO compliance for the URL shortener (details are [here](https://github.com/cds-snc/url-shortener/issues/251)).
=> Block all addresses access to port 22 and 3389

S3_log_bucket/README.md, S3_log_bucket/input.tf, S3_log_bucket/main.tf
[In April, AWS made it so that you could not add non-private ACLs inline with the S3 bucket. ](https://github.com/hashicorp/terraform-provider-aws/issues/28353)
Additionally, adding inline ACLs has been deprecated as of V4 of AWS provider.
This PR moves the ACL configuration outside of the S3 bucket and into a dedicated aws_s3_bucket_acl as well as setting the default ownership controls.
* Create new s3 resource using this module
=> Fixing acl association to S3 log bucket

cds_conformance_pack/README.md, cds_conformance_pack/input.tf, cds_conformance_pack/locals.tf, cds_conformance_pack/main.tf
Adds the ability to inject custom conformance rules alongside the conformance pack using a custom yaml file. This allows the ability to replace existing rules and add new ones.
ex - defining this override
```
Resources:
AccessKeysRotated:
Properties:
ConfigRuleName: access-keys-rotated-YOLO
InputParameters:
maxAccessKeyAge:
Fn::If:
- accessKeysRotatedParamMaxAccessKeyAge
- Ref: AccessKeysRotatedParamMaxAccessKeyAge
- Ref: AWS::NoValue
Source:
Owner: AWS
SourceIdentifier: ACCESS_KEYS_ROTATED
Type: AWS::Config::ConfigRule
```
yields this result:
=> feat: custom conformance yaml

rds/README.md, rds/input.tf, rds/main.tf
This PR adds the ability to log RDS security group change events to an SNS topic. Closes https://github.com/cds-snc/security-risk-register/issues/88
=> feat: add ability to log sg events to sns

lambda/README.md, lambda/main.tf
This relates to the following [issue](https://github.com/orgs/cds-snc/projects/13/views/29?pane=issue&itemId=24251338) where we want to measure lambda cold starts. I also added additional statistics such as the count invocations, how many cold starts were invoked, the percentage of cold starts, maximum Cold Start time, Average/Min/Max duration, Average Memory used, memory allocated and percentage memory used. 
Not sure at all if this is the right approach - ie to create cloudwatch query in the log insights so if there are better approaches, I am all ears!
=> Measure lambda cold starts (plus min/max duration & memory usage)

S3_scan_object/main.tf
Update the S3 scan object's transport lambda timeout to 2 minutes. This is to give it time to wait for an available Scan Files function to be available in the case of a cold start.
- #250
=> fix: increase default timeout of transport lambda

S3_scan_object/README.md, S3_scan_object/examples/existing_policy/main.tf, S3_scan_object/examples/simple/main.tf, S3_scan_object/input.tf, S3_scan_object/lambda/main.py, S3_scan_object/lambda/main_test.py, S3_scan_object/main.tf
Update the module's transport lambda to invoke `s3_scan_object` asynchronously as a response is not required for processing.
Also update the logging of the transport lambda and provide a way for module users to specify a log level.
- cds-snc/platform-core-services#297
=> fix: s3_scan_object async invoke scan

S3_scan_object/README.md, S3_scan_object/input.tf, S3_scan_object/main.tf
Remove the `s3_scan_object_function_arn` var
as it is no longer needed.
- cds-snc/platform-core-services#297
- cds-snc/platform-core-services#365
=> fix: remove unused var from s3_scan_object

notify_new_iam_user/README.md, notify_new_iam_user/cloudwatch.tf, notify_new_iam_user/functions/index.py, notify_new_iam_user/iam.tf, notify_new_iam_user/lambda.tf, notify_new_iam_user/locals.tf
The following changes were made:
- Updated the module code to live in zone us-east-1 in order for the CreateUser Cloudtrail log to be properly picked up. 
- Since the sre-internal topic lives in ca-central-1, needed to update the topic region
- Created a new cloudwatch log group that the lambda function will send output to.
- Removed an extra space for the username created and this was inserting an extra space in the sre-alert
- Updated documentation. 
If there is a better way to do this, I am all ears!
=> Update zones of lambda function & sns topic

.devcontainer/devcontainer.json
Just a quick change to add Azure CLI to the devcontainer settings as there are modules that are built for Azure
=> feat: add azure cli to devcontainer

.github/workflows/conftest/test_plan.tf, S3/README.md, S3/versions.tf, S3_log_bucket/README.md, S3_log_bucket/versions.tf
Update the S3 module version constraints to allow the v5 AWS provider.
These were added because it was expected that the v5 provider would have breaking changes for the deprecated attributes of the `aws_s3_bucket`, but the changes were not made.
=> fix: allow the AWS v5 provider for S3 modules

S3_log_bucket/main.tf
Fix the S3 bucket versioning resource so that it creates successfully if the bucket is marked as non-critical.
- https://github.com/cds-snc/terraform-modules/pull/263
=> fix: non-critical s3_log_access bucket

S3_log_bucket/README.md, S3_log_bucket/input.tf, S3_log_bucket/main.tf
Update the S3 versioning status to be directly set via the `versioning_status` variable.  This is being done because a bucket that has versioning `Enabled` cannot be set to `Disabled` and must instead go to `Suspended`.
Also updates the module to set versioning disabled by default as an access log bucket only has each log
written once.
- https://github.com/cds-snc/scan-files/pull/641
=> fix: directly set the S3 versioning status

gh_oidc_role/main.tf, gh_oidc_role/output.tf
Update the OIDC provider to trust all certificate thumbprints returned by GitHub.
- https://github.com/cds-snc/platform-core-services/issues/411
=> fix: trust all GitHub intermediate SSL certs

lambda/main.tf
Update the CloudWatch query definition to include the function name.  This will prevent name clashes for projects that are using this module more than once.
=> fix: add Lambda function name to query

S3_log_bucket/input.tf
Due to a rather silly and unreasonable terraform [requirement](https://developer.hashicorp.com/terraform/language/expressions/custom-conditions), we need to the error message to be "at least one full English sentence starting with an uppercase letter and ending with a period or question". Previously, it did not end with a period, so I just added it.
=> Adding a period to the end of the error message

gh_oidc_role/README.md, gh_oidc_role/main.tf
Added a warning to the gh_oidc_role when generating terraform docs to keep the version to below 4.0.0 since version 4.0.0 contains a breaking change (if someone even reads it...)
=> Add warning to keep version to below 4.0.0 for module

S3_scan_object/README.md, S3_scan_object/iam.tf, S3_scan_object/input.tf, S3_scan_object/kms.tf, S3_scan_object/main.tf
Update the `S3_scan_object` module to include a scan queue suffix.  This allows the module to be used more than once in a single AWS account.
- https://github.com/cds-snc/share-files-securely/pull/24
=> fix: add scan queue suffix

S3_scan_object/README.md, S3_scan_object/examples/existing_policy/main.tf, S3_scan_object/examples/simple/main.tf, S3_scan_object/iam.tf, S3_scan_object/input.tf, S3_scan_object/kms.tf, S3_scan_object/locals.tf, S3_scan_object/main.tf, S3_scan_object/s3.tf
Update the `S3_scan_objects` module so that multiple buckets can share the same SQS queue.
This allows a single AWS account to have multiple S3 buckets being scanned.
=> feat: share a single SQS queue

sentinel_alert_rule/main.tf
Add a dynamic incident_configuration block to default grouping to enabled when query_frequency is not PT5M.
=> feat: add dynamic incident config block

README.md, ecs/README.md, ecs/main.tf
Update the ECS module docs and add a link from the main README.
=> docs: fix readme and add link to ECS module

simple_static_website/README.md, simple_static_website/cloudfront.tf, simple_static_website/input.tf
This PR adds the ability for the user to configure the behaviour of the bucket to accommodate a single page app that does URL rewrites in the browser.
=> feat: add SPA config

simple_static_website/cloudfront.tf
Fixes a bug where the path needs to be absolute in the `response_page_path` attribute for the SPA config in the simple static page.
=> fix: Path bug

rds/README.md, rds/input.tf, rds/main.tf
Update the RDS cluster configuration to support the `backtrack_window` setting for `aurora-mysql` clusters:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Managing.Backtrack.html
This allows you to rewind the cluster to a specific point in time within the window, making it easier to recover from failed upgrades and security incidents.
- https://github.com/cds-snc/platform-core-services/issues/471
=> feat: support Aurora MySQL engine backtracking

rds/README.md, rds/cloudwatch.tf, rds/input.tf, rds/locals.tf, rds/main.tf
Update the RDS cluster resource to:
1. Copy resource tags to snapshots.
2. Allow for the export of database logs to CloudWatch.
If no logs are selected for export, the module defaults to sending `audit` logs for MySQL and `postgresql` for Postgres.
- https://github.com/cds-snc/platform-core-services/issues/471
=> fix: RDS copy tags to snapshot, enable logging

ecs/cloudwatch.tf
Truncating the name of the lambda function for Sentinel since "sentinel-forwarder" is not necessary since "SentinelForwarderLambda" is automatically added to the function name by the Sentinel terraform module. This fixes an error similar to this one:
=> Truncating the name since so that 64 characters are not exceeded. 

ecs/README.md, ecs/input.tf, ecs/main.tf
Update the module to allow users to specify a `volume` configuration.  This can then be used with the task bind mounts.
- https://github.com/cds-snc/platform-core-services/issues/480
=> feat: add ECS volume input

schedule_shutdown/README.md, schedule_shutdown/iam.tf, schedule_shutdown/input.tf, schedule_shutdown/lambda/schedule.py, schedule_shutdown/lambda/schedule_test.py, schedule_shutdown/locals.tf, schedule_shutdown/main.tf
Update the `schedule_shutdown` module to allow it to enable and disable CloudWatch alarms and Route53 healthchecks as part of the scheduled shutdown and startup.
- https://github.com/cds-snc/platform-core-services/issues/473
=> feat: scale CloudWatch alarm, Route53 healthcheck

.devcontainer/devcontainer.json, .github/workflows/ci.yml, schedule_shutdown/Makefile, schedule_shutdown/examples/simple/main.tf, schedule_shutdown/lambda/schedule.py, schedule_shutdown/tests/globals.tfvars, schedule_shutdown/tests/integration.main.tftest.hcl, schedule_shutdown/tests/unit.iam.tftest.hcl, schedule_shutdown/tests/unit.main.tftest.hcl
Add [Terraform unit and integration tests](https://developer.hashicorp.com/terraform/language/tests) to the `schedule_shutdown` module.
Add a new GitHub workflow to run these tests on PRs.
- Closes https://github.com/cds-snc/platform-core-services/issues/473
=> feat: `scheduled_shutdown` unit/integration tests

.github/workflows/terraform-apply.yml, .github/workflows/terraform-plan.yml, .gitignore, terraform/.terraform.lock.hcl, terraform/iam_oidc.tf, terraform/inputs.tf, terraform/provider.tf
Add a role that can be used by PRs to run the Terraform tests.
This will allow us to remove the IAM user with its hard-coded credential.
- #351
=> feat: add terraform-modules-test OIDC role

.github/workflows/terraform-apply.yml
Update the TF apply workflow so that terraform init is called first.
- #351 
- #352
=> fix: add missing TF init

.github/workflows/conftest/test_plan.tf, vpc/README.md, vpc/examples/high_availability/main.tf, vpc/examples/high_availability_single_nat/main.tf, vpc/inputs.tf, vpc/locals.tf, vpc/main.tf, vpc/tests/unit.custom_subnets.tftest.hcl, vpc/tests/unit.high_availability.tftest.hcl, vpc/tests/unit.high_availability_single_nat.tftest.hcl, vpc/versions.tf
Does the following: 
- allow a variable amount of availability zones  (will fail at compile time if the number of az's is higher then those available in a region.)
- removes the `high_availability` flag
- Allows you to specify the `cidrsubnet_newbits` as the existing functionality didn't work nice with a variable number of AZ's or a cidr range that is too small, defaults to `10`
- removes the deprecated `vpc = true` flag from inside the module and replaces it with `domain = "vpc"` to match the new syntax in the aws provider v5
BREAKING CHANGE - will no longer work with provders < 5
=> feat: add variable number of azs to VPC

client_vpn/README.md, client_vpn/output.tf
Add an output with the client VPN's CloudWatch log group name. This can be used for things like the Sentinel log forwarder's subscriptions.
=> fix: add client VPN output for CloudWatch log group

lambda/README.md, lambda/input.tf, lambda/main.tf
We want to add an alias name for the lambda function. This can be used to reference the lambda function, especially for deployment purposes.
=> Add an alias name for the lambda function

ecs/README.md, ecs/container_definition.tf, ecs/input.tf, ecs/main.tf, ecs/service_discovery.tf
Add service discovery to the ECS service creation.
Add the ability to override the task container's default `command`.
- https://github.com/cds-snc/platform-core-services/issues/536
=> feat: add ECS service discovery and task command override

ecs/cloudwatch.tf
Update the CloudWatch log group so that it includes the ECS service name.  This is being done to allow the module to define services in an existing cluster.
- https://github.com/cds-snc/platform-core-services/issues/536
=> fix: append service name to CloudWatch log group name

ecs/README.md, ecs/cloudwatch.tf, ecs/input.tf, ecs/locals.tf, ecs/service_discovery.tf
Update the module to allow the user to specify if they would like to append the service name to the CloudWatch log group name. This is being done to support existing use of this module since otherwise the log groups would be destroyed.
Update the service discovery's health check failure threshold to `1` as this is the only value that the AWS API will accept.
- https://github.com/cds-snc/platform-core-services/issues/536
- https://github.com/hashicorp/terraform-provider-aws/issues/35559
=> fix: ecs optionally append service name to log group

S3/main.tf
Update the module so that if no logging `target_prefix` is set, it defaults to blank.  This is to address a change in the AWS API where the `LoggingEnabled.TargetPrefix` request element is now required.
=> fix: set a blank target_prefix if none specified

.devcontainer/devcontainer.json, simple_static_website/README.md, simple_static_website/main.tf
Add a public access block that prevents all public access to the website's origin bucket.
=> fix: block public access to CloudFront origin S3 bucket

simple_static_website/README.md, simple_static_website/cloudfront.tf, simple_static_website/input.tf
Add the ability to specify lambda function associations with the website's CloudFront distribution.
- https://github.com/cds-snc/platform-core-services/issues/542
=> feat: add support for lambda function associations

spend_notifier/examples/main.tf
Changed the example to use a variable instead of the webhook to prevent people to accidentally commit a webhook URL as is into their code. The webhook that was used in the example was not active and is disabled, but wanted to make sure that it is clear that the webhook URL should be passed in as a variable since it is considered sensitive information.
=> Changing webhook url to be a variable. 

rds_activity_stream/README.md, rds_activity_stream/input.tf, rds_activity_stream/lambda.tf
Add variables that allow the decrypt lambda's memory size and timeout to be configurable.
=> feat: RDS activity stream config inputs for decrypt lambda

rds_activity_stream/README.md, rds_activity_stream/lambda.tf
Update the lambda dependencies to always download.  This will cause the lambda layer data archive to be available during Terraform operations.
The downside is that this will re-create the lambda layer on every Terraform apply but this bug is currently blocking the Notify Terraform workflows.
=> fix: RDS activity stream always download lambda dependencies

.devcontainer/devcontainer.json, .gitignore, rds_activity_stream/README.md, rds_activity_stream/lambda.tf, rds_activity_stream/scripts/decrypt_deps.sh
Update to use an [`external` data source](https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/external) to create the decrypt Lambda layer dependency zip file.  This allows us to create a deterministic zip file that will only change when the `requirements.txt` file is updated.
As a result, the Lambda layer will only be updated when there are dependency changes.
=> fix: RDS activity stream lambda external data source

sentinel_forwarder/main.tf, sentinel_forwarder/tests/unit.main.tftest.hcl
Update the Sentinel Forwarder module's authentication SSM parameter name to include the Lambda function name.
This allows multiple instances of the module to be used in the same AWS account.
- https://github.com/cds-snc/platform-core-services/issues/557
- https://github.com/cds-snc/site-reliability-engineering/issues/1215
=> fix: prefix SSM param name with function name

spend_notifier/lambda.tf
Update to Node.js 18.x Lambda runtime.
- https://github.com/cds-snc/platform-core-services/issues/560
=> fix: upgrade deprecated Node.js Lambda runtime

spend_notifier/examples/main.tf, spend_notifier/lambda.tf, spend_notifier/lambdas/spend_notifier/spend_notifier.js
Update the Lambda code to use the Node.js AWS SDK v3 which is bundled with Node.js 18+ runtime environments.
Update the Lambda runtime to Node.js 20.
- https://github.com/cds-snc/platform-core-services/issues/560
=> fix: upgrade to AWS SDK v3

rds/README.md, rds/locals.tf, rds/outputs.tf, rds/proxy_role.tf, rds/secret.tf
Add an output with the cluster's connection endpoint.
This will be used for scenarios where the RDS proxy needs to be bypassed like RDS blue/green deployments.
- https://github.com/cds-snc/platform-core-services/issues/561
=> chore: add RDS cluster endpoint output

rds/README.md, rds/security_group.tf
Update the RDS module to use standalone rules for the proxy security group.  
This will allow module consumers to more easily alter the security group by adding their own custom rules without a TF apply flip-flop on each change.
=> fix: RDS proxy use standalone security group rule

simple_static_website/main.tf
Adding an explicit allow effect to the document policy since previously our opa checks were failing. 
Thanks @patheard for the help!
=> Add an explicit effect to the policy document so that opa checks pass

sentinel_alert_rule/main.tf
Fix the sentinel alert module by removing the duplicate incident_configuration block.
=> fix: remove duplicate incident config argument

athena_access_logs/sql/lb_create_table.sql
Update the query used to create the load balancer table in Athena.
- https://docs.aws.amazon.com/athena/latest/ug/application-load-balancer-logs.html#create-alb-access-logs-table
=> fix: Athena SQL query to create a load balancer table

lambda/main.tf
Instead of having the Lambda statistics sitting in the root folder of the LogsInsight query listing, have these sitting in a folder of their own named `Lambda Statistics` for better organization.
Deploy some new lambdas after upgrading to latest lambda module version.
=> Put lambda statistics into a LogsInsight folder of their own `Lambda`

client_vpn/output.tf
The client certificate output was outputting the client key. Fixing.
TF Apply
=> Fix: Fixing the output for client vpn

simple_static_website/main.tf
[We are getting a weird issue where the "version" tag on tags and tags_all is getting created somewhere else. This causes confusion on the TF plans.](https://github.com/cds-snc/notification-terraform/pull/1399#issuecomment-2189529957) 
Not sure where these tags are coming from, but I figure we can safely ignore them.
TF Apply works
=> Simple Static Website - ignore "version" tag on lifecycle

rds/README.md, rds/cloudwatch.tf, rds/input.tf, rds/locals.tf, rds/main.tf, rds/moved.tf, rds/outputs.tf, rds/proxy_role.tf, rds/secret.tf, rds/security_group.tf, rds/tests/unit.main.mysql.tftest.hcl, rds/tests/unit.main.no.proxy.tftest.hcl, rds/tests/unit.main.postgres.tftest.hcl
Update the RDS module so that it can be used to create RDS clusters without an associated proxy.  The change includes a migration file so that existing users of the module will be able to upgrade without any breaking changes.
This is being done for projects that handle the connection pooling internally and do not want to pay extra for the proxy.  However, by default the module's behaviour will be to create the RDS proxy.
=> feat: create an RDS cluster without a proxy

ecs/main.tf
Update the ECS module so that if the latest task definition is being used, the latest task def revision is automatically added.
This will prevent TF plan flip-flops removing this revision if it has been set by another process.
=> fix: set ECS task revision when using latest task def

waf_ip_blocklist/README.md, waf_ip_blocklist/iam.tf, waf_ip_blocklist/input.tf, waf_ip_blocklist/lambda/blocklist.py, waf_ip_blocklist/lambda/blocklist_test.py, waf_ip_blocklist/lambda/query_lb.sql, waf_ip_blocklist/lambda/query_waf.sql, waf_ip_blocklist/main.tf
Update the module so that it can also optionally block IP addresses based on load balancer HTTP response codes:
- `403` from the load balancer
- `4xx` from the target group
- https://github.com/cds-snc/platform-core-services/issues/619
=> feat: block based on load balancer response

waf_ip_blocklist/lambda/blocklist.py
Updates one of the console logs in the WAF IP block list module to correctly display the new number of IPs added vs the total number blocked
Previous: 
`Updated WAF IP set with 9 new IPs.`
Fixed:
`Updated WAF IP set with 2 new IPs for a total of 9 blocked IPs.`
=> fix: Update console log message in waf_ip_blocklist

lambda_schedule/README.md, lambda_schedule/input.tf, lambda_schedule/locals.tf
Update the `lambda_schedule` module to allow the user to specify additional IAM policies for the Lambda's role.
- https://github.com/cds-snc/platform-core-services/issues/621
=> feat: allow custom Lambda schedule policies

.devcontainer/devcontainer.json, .github/workflows/terraform-apply.yml, .github/workflows/terraform-plan.yml, terraform/provider.tf
Update the TF state to have a unique name so that it can more easily be ignored by the AWS Nuke job.
Also updates Terraform and switches to use a lockfile so we can remove the DynamoDB dependency.
=> fix: give the TF state a unique name

vpc/README.md, vpc/main.tf
Updating the readme to indicated that the high_availability flag has been deprecated in the VPC module after v9.0.0 and include fixes on how to resolve the issue.
=> Update Readme to include VPC breaking v9.0.0 change

lambda_schedule/README.md, lambda_schedule/ecr_lifecycle.json, lambda_schedule/input.tf, lambda_schedule/main.tf
Add an input that allows the user to configure the architectures of the Lambda function.
Update the ECR policy to only keep the 10 most recently pushed images.
=> feat: add ability to set Lambda architectures

waf_ip_blocklist/README.md, waf_ip_blocklist/input.tf, waf_ip_blocklist/lambda/blocklist.py, waf_ip_blocklist/lambda/blocklist_test.py, waf_ip_blocklist/lambda/query_lb.sql, waf_ip_blocklist/main.tf
Add the ability to prevent some LB target response codes from causing an IP to get added to the blocklist.
The use case for this is when normal service flow can generate 4XX status codes that should not result in a user block.
=> feat: add LB response code skip list

DocumentDB/input.tf, DocumentDB/main.tf
Adds the `storage_type` option for DocumentDB clusters. Compared to standard storage, I/O-optimized storage offers better performance and cost efficiency for I/O-heavy workloads. For more information, see [Amazon DocumentDB cluster storage configurations](https://docs.aws.amazon.com/documentdb/latest/developerguide/db-cluster-storage-configs.html).
=> feat: add storage_type option for DocumentDB

ecs/README.md, ecs/output.tf
- Adds service port to ECS module outputs. This will be useful for the service discovery feature when we need to build the URL to access a specific service `${service-name}.${dns-name}:${service-port}`.
Note:
As stated in the AWS documentation, we do not really need to output the host port as the container port is the one that matters the most.
> <ins>For task definitions that use the awsvpc network mode, only specify the containerPort.</ins> The hostPort can be left blank or it must be the same value as the containerPort.
=> feat: add service port to ECS module outputs

ecs/output.tf
- Fixes ECS port output so that it handles null value
=> fix: ECS port output should handle null value

waf_ip_blocklist/lambda/blocklist.py, waf_ip_blocklist/lambda/blocklist_test.py, waf_ip_blocklist/main.tf
Set the target Athena region for the boto client.  This will avoid permission errors if Athena exists in a different region from the Lambda function.
=> fix: set region for Athena boto client

waf_ip_blocklist/README.md, waf_ip_blocklist/input.tf, waf_ip_blocklist/lambda/blocklist_test.py, waf_ip_blocklist/lambda/query_lb.sql
Adds the verifying of 5xx return status codes from the target to the load balancer query.
Ensures requests that are not handled properly by the application are also neutralized.
=> chore: Add 5xx to lb query for waf_ip_blocklist

guardduty_malware_s3/README.md, guardduty_malware_s3/cloudwatch.tf, guardduty_malware_s3/examples/simple/simple.tf, guardduty_malware_s3/input.tf, guardduty_malware_s3/tests/unit.main.tftest.hcl
Add alarms that will trigger if more than 10,000 files or 2GB of data have been scanned in a single day.
- https://github.com/cds-snc/platform-core-services/issues/755
=> feat: add GuardDuty Malware S3 alarms

sentinel_alert_rule/input.tf
Adding a validation for entity mapping that could cause `terraform apply` to fail
=> Adding validation for column_name field

.devcontainer/devcontainer.json, terraform/provider.tf
Fix the Terraform state as it was accidentally deleted by the AWS cleanup task.
=> fix: Terraform state for OIDC role
