- .github/workflows/lint.yml
- .github/workflows/scripts/run-shellcheck.sh
- .github/workflows/shellcheck.yml
- .gitignore
- README.md
- bin/generate-docs.sh
- user_login_alarm/.terraform-docs.yml
- user_login_alarm/README.md
- user_login_alarm/input.tf
- user_login_alarm/main.tf
- Module now takes in a set of account names to generate alarms for
- Closes #3
- Added a script that will use terraform-docs to automatically generated
README.md files
- Closes #2
> feat: multiple accounts and doc generation

- pub_priv_vpc/README.md
- pub_priv_vpc/flowlogs.tf
- pub_priv_vpc/inputs.tf
- pub_priv_vpc/locals.tf
- pub_priv_vpc/main.tf
- pub_priv_vpc/outputs.tf
- pub_priv_vpc/routetable.tf
Adds the ability to toggle off and on high availability mode really only works in ca-central-1 so beware if you want to stand up something in another region.
> feat: add high availability

- rds/outputs.tf
> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.
---
> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.
> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de …
> fix: expose the secret so we can use it in a lambda

- README.md
- rds/README.md
- rds/input.tf
- rds/main.tf
- updates documentation for RDS
- add link to RDS module in main README.md
- add the ability to turn off or on debug logging for proxy
Closes #25
> feat: add cloudwatch log group for rds proxy

- rds/README.md
- rds/input.tf
- rds/main.tf
- Add engine version as an input
- Add engine to instances
- Add the ability to turn off and on deletion protection
- Add the ability to toggle major version upgrades
- Default to 3 instances
> fix: issues with RDS

- rds/secret.tf
The new secret format was grabbed from here:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-proxy.html#rds-proxy-secrets-arns
> fix: update the secret provided to the proxy.

- .github/workflows/s3-backup.yml
- .github/workflows/security-scan.yml
* Adds a checkov security scan to the modules.
* Adds a fix for the S3 backup workflow so that it captures project history.
Closes #38
> feat: checkov security scan

- vpc/README.md
- vpc/main.tf
> fix: link to HA diagram in docs

- vpc/examples/high_availability/main.tf
- vpc/examples/single_zone/main.tf
- vpc/test/go.mod
- vpc/test/go.sum
- vpc/test/high_availability_test.go
- vpc/test/single_zone_test.go
- vpc/test/vpc_test.go
Add assertions to the VPC `single_zone` and `high_availability` tests to make sure resources are created as expected.
Related #29
> feat: add asserts for VPC unit tests

- rds/examples/two_instance_cluster/main.tf
- rds/outputs.tf
- rds/test/go.mod
- rds/test/go.sum
- rds/test/two_instance_cluster_test.go
Confirm that the RDS cluster and proxy resources are created as expected.
Closes #29
> feat: add asserts to RDS module tests

- .github/workflows/conftest/test_plan.tf
- lambda/iam_role.tf
Use the index of the policy in attaching a new policy
Add required tags to policy
> fix: policy attachment

- .github/workflows/conftest/test_plan.tf
- lambda/README.md
- lambda/iam_role.tf
- lambda/input.tf
> feat: allow for toggling of the AWSLambdaVPCAccessExecutionRole

- vpc/flowlogs.tf
> chore: add tags to flow log resources

- .modules
- attach_tf_plan_policy/Makefile
- attach_tf_plan_policy/README.md
- attach_tf_plan_policy/input.tf
- attach_tf_plan_policy/locals.tf
- attach_tf_plan_policy/main.tf
- gh_oidc_role/README.md
This creates a policy that allows access to dynamodb, s3 state bucket
and gives the ability to read secrets.
Closes #99
> feat: Module to create a policy for TFPlan Roles

- attach_tf_plan_policy/main.tf
> fix: reference to policy arn

- gh_oidc_role/README.md
- vpc/README.md
- vpc/outputs.tf
Please note `make docs` was run and so some unrelated doc changes are in this PR which is expected.
Closes #66
> feat: add main_route_table_id to outputs

- sentinel_forwarder/main.tf
Addresses the lambda best practice of adding the source account as an invoke condition.
ref: https://docs.aws.amazon.com/lambda/latest/dg/access-control-resource-based.html
> feat: add source account to invoke lambdas

- vpc/README.md
- vpc/examples/high_availability_single_nat/main.tf
- vpc/examples/high_availability_single_nat/provider.tf
- vpc/inputs.tf
- vpc/locals.tf
- vpc/main.tf
- vpc/routetable.tf
- vpc/test/high_availability_single_nat.go
- vpc/test/vpc_test.go
Adding the capability to only use one NAT Gateway (natgw). These are costly, so having the ability to only use one would help reduce costs when multiple aren't necessary.
> feat: option for 1 natgw when running in multiple az

- S3/main.tf
> fix: set bucket enabled if arn is set

- auto_revoke_sg_rules/Makefile
- auto_revoke_sg_rules/README.md
- auto_revoke_sg_rules/functions/sg_change_auto_response.py
- auto_revoke_sg_rules/iam.tf
- auto_revoke_sg_rules/input.tf
- auto_revoke_sg_rules/locals.tf
- auto_revoke_sg_rules/main.tf
Terraform module to remove any inbound rules that open up traffic to port SSH and RDP ports (22 and 3389 respectively)
> Auto mitigation and removal of any inbound rules opening up SSH and RDP

- README.md
This PR added a link to the sentinel_alert_rule module
> add link to sentinel alert rule

- sentinel_alert_rule/README.md
- sentinel_alert_rule/input.tf
- sentinel_alert_rule/main.tf
This PR adds an optional variable: `techniques` for the sentinel alert rule module.
> add variable techniques

- sentinel_alert_rule/README.md
- sentinel_alert_rule/input.tf
Just updating the docs to match the actual defaults in the input.tf
> fix: docs to match actual defaults

- notify_new_iam_user/README.md
- notify_new_iam_user/input.tf
Change function name from `required` to `optional`
> fix: function name changed to optional

- S3_scan_object/examples/existing_policy/main.tf
- S3_scan_object/examples/simple/main.tf
- athena_access_logs/examples/simple/main.tf
- cds_conformance_pack/README.md
- cds_conformance_pack/main.tf
Modifying the terraform module to be in the correct format based on the terraform documentation - https://developer.hashicorp.com/terraform/language/modules/sources#modules-in-package-sub-directories
> Modifying the module reference in terraform modules 

- README.md
- cds_conformance_pack/README.md
- cds_conformance_pack/main.tf
Modifying the terraform module to be in the correct format based on the terraform documentation - https://developer.hashicorp.com/terraform/language/modules/sources#modules-in-package-sub-directories
> Making changes to module links

- ecs/README.md
- ecs/examples/simple/main.tf
- ecs/input.tf
- ecs/main.tf
Add the ability of the ECS Module to be able to pass your own roles.
> Pass your own IAM roles

- client_vpn/input.tf
Update the validation messages so they meet Terraform requirements.
> fix: client VPN validation messages

- simple_static_website/README.md
- simple_static_website/acm.tf
- simple_static_website/input.tf
- simple_static_website/main.tf
- simple_static_website/route53.tf
Added a variable so you can set the s3 bucket name
> Added a variable to set s3_bucket_name

- simple_static_website/README.md
- simple_static_website/examples/simple/main.tf
- simple_static_website/examples/simple/provider.tf
- simple_static_website/main.tf
Update the docs with the new `dns` provider and add an example.
> chore: update docs and add example

- simple_static_website/README.md
- simple_static_website/cloudfront.tf
- simple_static_website/input.tf
Added a bool variable that decides whether we fwd query strings to origin or not.
> Added a bool variable for cloudfront

- lambda/main.tf
Update the lambda statistic query log group name.
> fix: lambda statistic query log group

- lambda/README.md
- lambda/input.tf
- lambda/main.tf
Update the module to include a variable to allow for the function version to be published.
- https://github.com/cds-snc/platform-core-services/issues/548
> feat: publish lambda function version

- rds/README.md
- rds/outputs.tf
Update the RDS module to include the cluster ARN as an output.
> chore: add RDS cluster ARN output

- rds_activity_stream/kinesis.tf
- rds_activity_stream/lambda.tf
- rds_activity_stream/locals.tf
- rds_activity_stream/main.tf
- rds_activity_stream/tests/unit.main.tftest.hcl
Add missing common tags and update the resource names created by the `rds_activity_stream` module to make things more consistent.
> fix: add common tags and update resource names

- sentinel_forwarder/README.md
- sentinel_forwarder/outputs.tf
Add the Sentinel forwarder Lambda function name as a new output.
> feat: add Sentinel forwarder function name output

- .devcontainer/devcontainer.json
Update the devcontainer to include the AWS CLI.
> chore: add AWS CLI to devcontainer

- simple_static_website/README.md
- simple_static_website/cloudfront.tf
- simple_static_website/input.tf
Add the ability of the simple static website to use a WAF.
> Adding waf to the module

- sentinel_alert_rule/main.tf
Fixing the incident configuration dynamic block
> Fix the incident_configuration block 

- gh_oidc_role/main.tf
Unpinning the OIDC thumbprints
> feat: unpin the thumbprints

- client_vpn/README.md
- client_vpn/output.tf
I need the client vpn id for some scripts I want to run, so adding it as an output in the module.
TF apply works
Tested that the output works locally.
> feat: Adding client vpn endpoint output

- S3/main.tf
Add ability to specify S3 lifecycle storage transition and non-current version expiration rules.
- https://github.com/cds-snc/platform-core-services/issues/609
> feat: add lifecycle storage transition and non-current version rules

- DocumentDB/README.md
- DocumentDB/examples/basic_setup/main.tf
- DocumentDB/examples/secured_setup/main.tf
- DocumentDB/input.tf
- DocumentDB/locals.tf
- DocumentDB/main.tf
- DocumentDB/outputs.tf
- README.md
A new module that allows us to create a DocumentDB database.
> New DocumentDB Terraform module

- .github/workflows/docs.yml
Update the error message for the doc check to be more informative.
> fix: improve error message for doc check
